spring:
  profiles:
    active: dev

jwt:
  secret-key: "this-is-coffee-and-taste-api-server"

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://coffee-and-taste.kro.kr/coffee_and_taste
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

open-api:
  url: https://coffee-and-taste.kro.kr
  description: production

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      data-locations: classpath*:data.sql

  h2:
    console:
      enabled: true

open-api:
  url: http://localhost:8080
  description: development
